# docker compose --env-file .env.mongo --env-file .env.network -f mongo.yml up -d
services:
  mongo:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data/mongo:/data/db
    networks:
      - gldev

networks:
  gldev:
    name: ${NETWORK_NAME}
    external: true
