# docker compose --env-file .env.mysql8 --env-file .env.network -f mysql8.yml up -d
services:
  mysql8:
    image: mysql:8
    container_name: mysql8
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    ports:
      - '3308:3306'
    expose:
      - '3306'
    volumes:
      - './data/mysql8-data/db:/var/lib/mysql'
    networks:
      - gldev

networks:
  gldev:
    name: ${NETWORK_NAME}
    external: true
