# docker compose --env-file .env.postgres --env-file .env.network -f postgres.yml up -d
services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: postgres
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    networks:
      - gldev

networks:
  gldev:
    name: ${NETWORK_NAME}
    external: true
